### ISSUE TITLE
Errors during signup and approval

### ISSUE THREAD

**Issue by sirkitree** [backdrop-contrib/pathauto#10]
I had a user come to my site and sign up and they recieved this error message:

---

Warning: Parameter 1 to pathauto_user_insert() expected to be a reference, value given in module_invoke_all() (line 884 of /var/www/beta.vrsites.com/docroot/core/includes/module.inc).

---

I then approved the account and upon submit recieved another error message:

---

Warning: Parameter 1 to pathauto_user_update() expected to be a reference, value given in module_invoke_all() (line 884 of /var/www/beta.vrsites.com/docroot/core/includes/module.inc).

---

**Comment by qster123** [comment]
Does this help? http://stackoverflow.com/questions/8512535/php-error-warning-parameter-1-expected-to-be-a-reference

**Comment by quicksketch** [comment]
`hook_user_insert/update/delete()` now no longer takes 3 arguments, it's just the `$account`, per https://api.backdropcms.org/node/26867. I'll file a PR to fix this.

**Comment by quicksketch** [comment]
I just pushed this as a commit instead of a PR: https://github.com/backdrop-contrib/pathauto/commit/7ed5cf3d151366d9df6cc77f572976bdc6fccd9d. Thanks @sirkitree for reporting this!
