### ISSUE TITLE
Request to add a maintainer (quicksketch)

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/pathauto#13]
Hi @enzolutions! Thanks for porting this and the Token module. Would you be okay if I were added to the list of maintainers for this module? Pathauto (some or all of it) is targeted to be included in the next minor release of Backdrop, so we'll need to coordinate to make sure that we have a path forward to including it in core. Thanks!

**Comment by quicksketch** [comment]
Crosslinking with the same request for Token: https://github.com/backdrop-contrib/token/issues/3

**Comment by enzolutions** [comment]
Sure Nate

You have the roadmap clear, if you can create tasks for specific tasks I could try to help you

**Comment by quicksketch** [comment]
Thanks @enzolutions! First things, I'll go through our list of issues, looks like there are a number of items people have run into already.

**Comment by quicksketch** [comment]
Thanks, I'll add myself to the maintainers as part of https://github.com/backdrop-contrib/pathauto/issues/2.

**Comment by enzolutions** [comment]
cool

**Comment by quicksketch** [comment]
Fixed up as part of https://github.com/backdrop-contrib/pathauto/issues/2. Thanks Enzo!
