### ISSUE TITLE
Warning: Illegal offset type in pathauto_cleanstring() (line 189 of pathauto.inc

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/pathauto#16]
After successfully creating a page:

```
- Warning: Illegal offset type in pathauto_cleanstring() (line 189 of C:\www\backdrop\modules\pathauto\pathauto.inc).
- Warning: Illegal offset type in pathauto_cleanstring() (line 235 of C:\www\backdrop\modules\pathauto\pathauto.inc).
Status message Basic page Test has been created.
```

**Comment by quicksketch** [comment]
Thanks @klonos. Man, the use of "language" and "langcode" in Pathauto is kind of crazy! I think all the changes are side-effects of https://www.drupal.org/node/1216094. This will take a little work to get `langcode` used consistently.

**Comment by klonos** [comment]
Yeah I guessed so. Well I'm here to test as you fix things. We'll get it right eventually :)

**Comment by quicksketch** [comment]
Okay, I think I got them all in https://github.com/backdrop-contrib/pathauto/commit/4fb97d80b258ffdf2aaf139061287074d0120151! Thanks to the tests, I'm feeling relatively confident about things now. At least they're all passing with no errors. I even ran across a core bug with Taxonomy terms (https://github.com/backdrop/backdrop-issues/issues/676), nice.

**Comment by klonos** [comment]
Yep, fixed now. Thanx :)
