### ISSUE TITLE
Your README is all kinds of messed up

### ISSUE THREAD

**Issue by sirkitree** [backdrop-contrib/pathauto#2]
It says it's the port of the token module?

**Comment by sirkitree** [comment]
So I was going to start cleaning this up but noticed there is a README.txt as well with this project.

In order to maintain compatibility and keep up with development on the Drupal version of this module, it might be better to simply remove the README.md and utilize their README.txt. Or is it better to have a separate file so that you don't have to worry about changing the README.txt file when synchronizing new features from the Drupal module. Do you even plan on keeping up with changes to the Drupal module?

**Comment by sirkitree** [comment]
In @quicksketch's recent port of codefilter, you'll notice he changed the README.txt into a README.md

https://github.com/backdrop-contrib/codefilter/commit/812b38a64857d00271c6e2d2a3aca9398f66cb0f#diff-2

**Comment by quicksketch** [comment]
I'll fix this up, as enzo has approved of my co-maintaining in https://github.com/backdrop-contrib/pathauto/issues/13. We need to get Pathauto in good shape in order to prepare it for core.

**Comment by quicksketch** [comment]
Fixed this up in https://github.com/backdrop-contrib/pathauto/commit/1b145b729111f9fe1d2cae248a7b340ceda06fe5. Thanks!
