### ISSUE TITLE
All Drupal 7 settings lost after upgrade.  No upgrade path?

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/pathauto#4]
Thanks for porting this module.  Unfortunately it looks like the upgrade path is missing(!?) All the settings I had set in Drupal seven have been lost after porting a site to Backdrop.

**Comment by quicksketch** [comment]
Fixed in https://github.com/backdrop-contrib/pathauto/commit/f302e140b5bd38a2b9147654360c0b3df84f4431.

**Comment by quicksketch** [comment]
Note that unfortunately the previous pathauto.install file contained 6xxx updates, which shouldn't happen (it shouldn't contain 7xxx updates either), but for updates that are before 7000, Backdrop believes that these are updates that apply to it, so Pathauto's schema_version in the system table is going to be in the 6000s on any site that installed Pathauto prior to this fix. That means that any existing sites will never see any updates, including the one added here.

I can't think of a way to fix this, but considering the number of sites running this early port of Pathauto is probably less than 20, I think we'll just have to let those sites work out the issue.

**Comment by herbdool** [comment]
That makes sense, thanks for the explanation. I had deleted the 6xxx and
7xxx updates on the modules I ported but only because I had looked at an
example. It might be useful to put this info explicitly in the api
documentation.

**Comment by quicksketch** [comment]
Added a small section on this to https://api.backdropcms.org/node/28621, and mentioned that you should also provide a `hook_update_last_removed()` to indicate which updates you've removed.

If you're running the initial port of Pathauto, you can "fix" your installation by updating the "schema_version" column in your "system" table to be 1000.
